# un progetto è un raggruppamento logico delle app gestite da ArgoCD (p.es. per team)
# questo permette p.es. di definire:
# - RBAC
# - source repo e revision
# - destination namespace
# ecc ecc
# le app che raggruppa questo progetto sono presenti nel repo argocd-production/helm/templates (sono 2)

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production project
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'