# questo è il descrittore dell'applicazione argocd devops-paradox, parte del progetto descritto nel project production
# descritto nel file project.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # questo è il progetto a cui questa applicazione appartiene
  project: production
  # dove è il codice? sul path helm del repo https://github.com/vfarcic/devops-paradox.git alla revision HEAD
  source:
    path: helm
    repoURL: https://github.com/aleMessoMale/devops-paradox.git
    targetRevision: HEAD
    # sovrascrivi quanto presente nel file values.yaml con questi valori
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: devopsparadox.com
      version: v3
  # dove devi deployare l'applicazione devops-paradox? In che k8s server?
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    # di default questi valori son entrambi a false
    automated:
      # questo indica che qualsiasi azione manuale viene immediatamente revertata a quanto presente nel codice
      selfHeal: true
      # questo indica che se cancelli qualcosa dal repo, le risorse vengono cancellate da k8s
      prune: true
